= Neo4j Examples around SDN6, older SDN+OGM and general driver usage.

NOTE: All examples have been valid and accurate at the time of their indivual last commit.
      Right now, I am not tracking all the updates to the libraries, not even the ones I maintain myself as a Neo4j employee.
      I do my best to keep the examples up to date. In case anything is odd, broken or really utterly outdated, please open an issue.

A somewhat curated list of Neo4j examples and tips, mostly around SDN with OGM (SDN 5.x), SDN 6 (previously SDN/RX) and testing.

* https://michael-simons.github.io/neo4j-examples-and-tips/ogm_sdn_knowledge_base.html[OGM and SDN knowledge base]
* https://michael-simons.github.io/neo4j-examples-and-tips/understand_the_type_system.html[Understand the Neo4j Cypher and OGM type system]
* https://michael-simons.github.io/neo4j-examples-and-tips/using_multiple_session_factories.html[Use multiple, different connections to Neo4j instances in a Spring Boot application]
* https://michael-simons.github.io/neo4j-examples-and-tips/use_dynamic_finder.html[Create SDN repositories that find nodes by arbitrary properties]
* https://michael-simons.github.io/neo4j-examples-and-tips/what_are_the_building_blocks_of_sdn_and_ogm.html[What are the building blocks of SDN and OGM?]
* https://michael-simons.github.io/neo4j-examples-and-tips/validate_transaction_settings.html[Validate your Neo4j transaction settings]
* https://michael-simons.github.io/neo4j-examples-and-tips/sdn_and_causal_cluster.html[Use causal cluster support]

TIP: The most recent SDN6 examples are link:/examples/sdn6[SDN6 (Plain SDN+Spring WebMVC)] and link:/examples/sdn6-rest[SDN6-REST (SDN+Spring Data REST)].

While the link:/examples[examples] here are more use case driven, I also actively maintain https://github.com/michael-simons/neo4j-from-the-jvm-ecosystem[neo4j-from-the-jvm-ecosystem]. There I have a couple of options how to use Neo4j in different frameworks and all of them provide the same API to the outside world. Those examples come with a unified build and tck script.
