= Testing your Neo4j-based Java application
Michael Simons <michael.simons@neo4j.com>
:doctype: article
:lang: de
:listing-caption: Listing
:source-highlighter: coderay
:icons: font
:sectlink: true
:sectanchors: true
:xrefstyle: short
:tabsize: 4

In this post I'm gonna present different approaches how you can test your Neo4j-based application.
As you might know, Neo4j can be accessed from a variety of languages - Go, Python and JavaScript being some of them - this post focuses on Java based applications.
I'm an engineer on Neo4j's Spring Data team, so this is where my focus usually is.

There are several aspects that needs to be considered while making the decision for or against a certain test setup.

* Are you developing a stored procedure for the database itself?
* Are you using the official https://github.com/neo4j/neo4j-java-driver[Java-driver] to issue Cypher-queries directly over Bolt?
* Are you using an Object-Graph-Mapping library like https://github.com/neo4j/neo4j-ogm[Neo4j-OGM] to build an application-side domain model?
* Did you add https://github.com/spring-projects/spring-data-neo4j[Spring Data Neo4j] to the mix to take advantage of the Spring ecosystem?

I'll cover those four scenarios which allow for a good comparison of the options we have at hand for testing queries or a domain model against the Neo4j database.

I'm gonna use https://junit.org/junit5/[JUnit 5] in all scenarios.
At the beginning of 2019, there's hardly any reason not to use JUnit 5 in new projects.
All Neo4j specific techniques demonstrated in this post can be be applied with some adaption to JUnit 4 as well.

NOTE: The examples in this article will all deal with spatial values and the functions defined there on.
The spatial datatype `point` is new since Neo4j 3.4 and Neo4j-OGM will support it out-of-the-box in Neo4j-OGM 3.2 and SDN 5.2.

== Neo4j test-harness

NOTE: The full example how to use the test-harness for custom Neo4j extension is on Github: https://github.com/michael-simons/neo4j-sdn-ogm-tips/tree/master/examples/using-the-test-harness[using-the-test-harness].

=== Testing custom Neo4j extensions

Neo4j can be extended with https://neo4j.com/docs/java-reference/3.5/extending-neo4j/procedures/[custom procedures] and functions.
One can also add https://neo4j.com/docs/java-reference/3.5/extending-neo4j/http-server-extensions/[unmanaged server extensions] to Neo4j, that expose arbitrary JAX-RS endpoints from the database.
In all three of them one can interact directly with the database API for all kind of functions that require direct interaction with the kernel for the highest degree of performance or flexibility.

This is where the Neo4j test-harness comes in.
The test-harness is a special variant of an embedded Neo4j instance with hooks to provide test fixtures and adding your custom procedures and extensions.

Given the following user defined procedure, which is part of this link:{examples-gh-ref}/using-the-test-harness[project]:

[source,java]
[[location-conversion]]
.LocationConversion.java, Converts legacy-style locations into proper points.
----
include::{examples}/using-the-test-harness/src/main/java/org/neo4j/tips/testing/using_the_test_harness/LocationConversion.java[tags=location-conversion]
----

The `LocationConversion` operates directly on the graph database nodes for optimal performance.
It is meant to be run server side with a call like this: `CALL examples.convertLegacyLocation(nodes)`.
If you followed the instructions on how to package your stored procedures you would have ended up with a JAR file containing the executable code.
Do you want to repackage it, stop your server and upload it everytime for testing it?
Probably not.

Enter the the test-harness:

[source,xml]
[[test-harness-dep]]
.pom.xml, Dependencies for test-harness
----
include::{examples}/using-the-test-harness/pom.xml[tags=test-harness-dep,indent=0]
----

There's a variant `neo4j-harness-enterprise` that matches the commercial enterprise version of Neo4j, too.

With JUnit 5 you don't need a `@Rule` to start it as JUnit 5 supports non-static initialization methods for tests when the lifecycle of the test is set to `PER_CLASS`.

[source,java]
[[test-harness-setup]]
.GeometryToolboxTest.java, Setup of the test-harness
----
include::{examples}/using-the-test-harness/src/test/java/org/neo4j/tips/testing/using_the_test_harness/GeometryToolboxTest.java[tags=test-harness-setup]
----
<1> The lifecycle of this test should be `PER_CLASS, so that `initializeNeo4j()`, annotated with `@BeforeAll` runs exactly once.
<2> The variable `embeddedDatabaseServer` to hold a reference to the server during all tests.
<3> `initializeNeo4j()` runs before all tests and uses a builder to create a test server, the builder provides interfaces for registering
<4> custom procedures and functions as well as
<5> fixtures, either through Cypher statements like here, files or even functions.
<6> finally, start the server

Now it's really easy to use the server provided by the harness.
I have added the Java-Driver as test-dependency to the project and open up a connection as against a standalone server-instance or cluster:

[source,java]
[[test-harness-usage1]]
.GeometryToolboxTest.java, Example usage of the test server
----
include::{examples}/using-the-test-harness/src/test/java/org/neo4j/tips/testing/using_the_test_harness/GeometryToolboxTest.java[tags=test-harness-usage1,indent=0]
----

=== Using the test-harness for application level tests

Technically, the test-harness and the embedded server, reachable through `ServerControls`, can be used for application-level-testing.
Besides the Bolt-URI it exposes the HTTP-URI as well as the embedded graph database instance itself.
Both URIs use random, free ports and thus allow tests in parallel.
The `ServerControls` are an autoclosable resource and as they start relatively quick, they can be fired up multiple times.

It comes with a price, however:
In the end it is a full blown Neo4j instance with all the dependencies.
You might not want those dependencies in your application, not even in the test scope.
The other disadvantage is the fact, that you're running the database inside the same JVM as your application.
Most of the time this is not what production looks like.
While being on the same JVM is the correct place for stored procedures, it is not for applications.
Using an embedded database for testing your application code might lead you into a false sense of safety.

== Neo4j Testcontainer

NOTE: The full example how to use the Testcontainers Spring Data Neo4j based applications is on Github: https://github.com/michael-simons/neo4j-sdn-ogm-tips/tree/master/examples/using-testcontainers[using-testcontainers].

What are https://www.testcontainers.org[Testcontainers]?

[quote, Testcontainers.org]
____
Testcontainers is a Java library that supports JUnit tests, providing lightweight, throwaway instances of common databases, Selenium web browsers, or anything else that can run in a Docker container.
____

http://twitter.com/frant_hartm[František Hartman] from  GraphAware wrote a very details article about https://graphaware.com/docker,/testing/2018/12/16/integration-testing-with-docker-neo4j-image-and-testcontainers.html[Integration testing with Docker Neo4j image and Testcontainers].
František already covered a lot here and you should check this out.

In the meantime, our pull request has landed in Testcontainers.
https://www.testcontainers.org/usage/neo4j_container.html[Neo4j container] describes the basic usage of the official container.

=== General setup of Testcontainers with JUnit 5

As stated earlier, I have become a big fan of JUnit 5.
Nice assertions are one reason, package private test methods, better lifecycle management and extensions are another.

Testcontainers comes with support for JUnit 5.
<<testcontainers-neo4j-junit5-deps>> shows all the necessary dependencies:

[source,xml]
[[testcontainers-neo4j-junit5-deps]]
.pom.xml, Dependencies for JUnit, Testcontainers and the Neo4j Testcontainer
----
include::{examples}/using-testcontainers/pom.xml[tags=testcontainers-neo4j-junit5-deps,indent=0]
----

At the time of writing, `testcontainers.version` is `1.10.5` and `junit-jupiter.version` is `5.3.2`.

I recommend the following setup for an integration test with Testcontainers:

[source,java]
[[minimal-neo4j-testcontainer-setup]]
.PlainOGMTest.java, Mininal test setup
----
include::{examples}/using-testcontainers/src/test/java/org/neo4j/tips/testing/using_testcontainers/PlainOGMTest.java[tags=minimal-neo4j-testcontainer-setup,indent=0]
----
<1> When run, extend this test-class with the `@Testcontainers` extension
<2> The extension will look for all attributes marked as `@Container` and start and stop them according to their lifecycle. Here, `databaseServer` points to our Neo4j Testcontainer.
<3> Create (but don't start) a `Neo4jContainer`

As JUnit 5 tests have a default lifecycle of `PER_METHOD`, shared state needs to be defined as static attributes of the test.
Hence, the definition of the Testcontainer as a `static` attribute.
This way, the  container is started before all tests and closed afterwards.
If the container is defined as an instance attribute, it's restarted before each individual test.

While it is possible to change the lifecycle of the test class to `PER_CLASS` instead of `PER_METHOD`, it's a bit harder later on to configure it for Spring Boot Test-Slices.

Also applicable for both plain Neo4j-OGM and SDN test is the way to provide a test-fixture.
This can be done in a `@BeforeAll` method like this:

[source,java]
[[prepare-test-data]]
.PlainOGMTest.java, Prepare test data
----
include::{examples}/using-testcontainers/src/test/java/org/neo4j/tips/testing/using_testcontainers/PlainOGMTest.java[tags=prepare-test-data,indent=0]
----
<1> `databaseServer` is the container we defined and started above. It provides access to the databases password
<2> The container provides an accessor to the Bolt-URI which contains a random port

The `@BeforeAll` method is invoked once before all tests.
I provide the test data over Bolt, so I have the Neo4j Java-Driver on the classpath.
Having a static string here is one option, but you can read in your test-data anyway you want.

=== Using with Neo4j-OGM

The only thing you need to test your business logic based on Neo4j-OGM and queries is a Neo4j-OGM `SessionFactory`.
I recommend defining it as a static variable through a second `@BeforeAll` method in the test as well:

[source,java]
[[prepare-sessionfactory]]
.PlainOGMTest.java, Create the `SessionFactory`
----
include::{examples}/using-testcontainers/src/test/java/org/neo4j/tips/testing/using_testcontainers/PlainOGMTest.java[tags=prepare-sessionfactory,indent=0]
----

Again: No hardcoded password, no hardcoded Bolt-URI.
The Neo4j-Testcontainer provides this.

One possible test with the above data could be this:

[source,java]
[[example-test]]
.PlainOGMTest.java, A simple test
----
include::{examples}/using-testcontainers/src/test/java/org/neo4j/tips/testing/using_testcontainers/PlainOGMTest.java[tags=example-test,indent=0]
----

This test runs over the network against a "real", server-mode Neo4j-instance.
Just as your application hopefully will.

=== Using with Neo4j-OGM and SDN, DataNeo4jTest

For me there's no good reasons to start new Spring projects without Spring Boot.
Spring Boot brings you - among other nice things - https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html[autoconfigured tests] and more important, test slices.
Test slices deal specifically with certain, technical layers of your application.
Being either database layer, service layer or just the web-frontend.

Regarding the database layer it's an integration test very much focussed on interaction with the database.

The Neo4j test-slice is called `@DataNeo4jTest`

[source,java]
[[sdn-neo4j-testcontainer-setup]]
.SDNTest.java
----
include::{examples}/using-testcontainers/src/test/java/org/neo4j/tips/testing/using_testcontainers/SDNTest.java[tags=sdn-neo4j-testcontainer-setup,indent=0]
----
<1> This activates Spring Datas repository layer and also provides Spring Boot's JUnit 5 extensions
<2> A `@TestConfiguration` adds to Spring Boots config but doesn't prevent autoconfiguration
<3> A bean of Neo4j-OGMs configuration will be created to configure the `SessionFactory` of Spring Data Neo4j
<4> JUnit 5 together with Spring Boots extension allow constructor based injection, even in tests

Now you can test against the `ThingRepository` which is shown in <<thing-repository>>

[source,java]
[[thing-repository]]
.ThingRepository.java, a Spring Data Neo4j repository
----
include::{examples}/using-testcontainers/src/main/java/org/neo4j/tips/testing/using_testcontainers/domain/ThingRepository.java[tags=thing-repository,indent=0]
----

A "boring" test would look like this:

[source,java]
[[boring-sdn-test]]
.SDNTest.java
----
include::{examples}/using-testcontainers/src/test/java/org/neo4j/tips/testing/using_testcontainers/SDNTest.java[tags=boring-sdn-test,indent=0]
----

Why is this boring?
Because we're basically testing whether Spring Datas query derivation works or not.

Testing `findThingWithGeometry` is much more interesting, as you may recognize `examples.getGeometry(t)` as our own, custom procedure.
How do we get this into the test container?
Turns out the authors of Testcontainers thought of a method to mount stuff in the container before it starts.

I packaged the custom stored procedures from the beginning of this article into a JAR files name `geometry-toolbox.jar` and added it to the test resources.
With this the Testcontainer can be created like this:

[source,java]
[[copy-plugin]]
.SDNTest.java
----
include::{examples}/using-testcontainers/src/test/java/org/neo4j/tips/testing/using_testcontainers/SDNTest.java[tags=copy-plugin,indent=0]
----

The plugin-jar get's copied into the right place inside the container and is recognized by Neo4j during startup.
The test data for the second test isn't hardcoded like in `PlainOGMTest.java`.
I copied over the `graph.db` folder from my "production" instance to the test resources.
Calling `withClasspathResourceMapping()` maps it into the containers `/data/` volumne, where Neo4j expects the database.
In a real-world test you probably have that data folder somewhere else and not in your project.
In such cases, you would use `withFileSystemBind()` of the Testcontainer.
Anyway, given the same test data as in <<prepare-test-data>>, a not so boring test now is green:

[source,java]
[[not-boring-sdn-test]]
.SDNTest.java
----
include::{examples}/using-testcontainers/src/test/java/org/neo4j/tips/testing/using_testcontainers/SDNTest.java[tags=not-boring-sdn-test,indent=0]
----

And with that, we just have tested an Spring Data Neo4j based Neo4j-application including custom plugins end-to-end.
Starting with the plugins and ending up with an integration test.

=== Summary

When writing custom extensions, you want a quick feedback loop for all of your tests.
You're also very close to the server in all cases.
The test-harness provides you with the fastest feedback loop possible and doesn't expose your code to more than you actually need.
Your code is right there at the server level.
The test-harness and the embedded, customizable instance of Neo4j should be your first choice when testing custom Neo4j extensions.
It is also a good choice for infrastructure code like Neo4j-OGM and Spring Data Neo4j itself.
Neo4j-OGM runs against an embedded graph, over Bolt and HTTP, so it must be tested against all of those.
The test-harness provides good support for that.

The main advantage of using a Testcontainer is the fact that reassambles your later application setup the most.
While there are some use cases, most applications should not run an embedded version of Neo4j.
Think about it: In a microservices world, where you usually more than one instance of an application running, should each instance bring it's own database?
You cannot run Neo4j in https://neo4j.com/docs/operations-manual/current/clustering/[Causal Cluster mode] in an embedded scenario, so you have to synchronize those instances.
Furthermore: If your application goes down, so would your database.

The generic Testcontainer or the dedicated Neo4j-Testcontainer gives an easy way to bring up new, clean database instances for each test.
Thus, your tests are independent of each other and you won't have interference in your test data from concurrent tests.

So please keep the following in mind while your design your integration tests:

* The topology of your test should reassemble your target topology as much as possible
* Try to use a dataset that is comparable in size to your production dataset

Testcontainers help a lot to achieve the first item.
Whether you can get your hands on a dataset that is similar to your production data set, depends probably on your surroundings and organization.
If it is possible however, you could create a custom Neo4j Docker image and use that one as a basis for the Testcontainer in your CI.
